version: '3.9'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./pharma.db:/app/pharma.db
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend/vite-project:/app
    command: npm run dev -- --host
